Update example for nomad 1.0
hashicorp/nomad-autoscaler pull request #326
Opened 2021-01-03 23:11 UTC by trilom

Since this example uses the latest nomad it no longer works with 1.0 because of the network stanzas.

I went through and got it working with the following configuration, but have not tested it against a networked cluster to verify it's working as it is intended to on a scale greater than 1.

There might need to be more work done I am working on another project that will ultimately validate this work but is not complete.

Thanks

2021-01-03 23:11 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/nomad-autoscaler?pullRequest=326)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/nomad-autoscaler?pullRequest=326)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)


---
**trilom** seems not to be a GitHub user.
You need a GitHub account to be able to sign the CLA. If you already have a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/nomad-autoscaler?pullRequest=326).</sub>

2021-01-04 10:24 UTC, jrasell requested changes
Thanks so much for working on this @trilom.

A meta comment, which duplicates across the job specification files is that additions are not formatted in accordance to HCL formatting and would be great to have fixed. Taking the new http port addition to the `autoscaler.nomad` file, the formatted port addition would look like:
```hcl
port "http" {
  to     = 8080
  static = 8080
}
```

It also seems the new `nomad_autoscaler_telemetry.json` file is unused and a duplicate of the file with the same name under the `shared` directory. Can this addition therefore be removed?

2021-01-04 10:24 UTC, jrasell commented on demo/vagrant/horizontal-app-scaling/jobs/autoscaler.nomad
> +        network_mode = "host"
What is the reason the network mode param was added? I don't believe we need it.

2021-01-04 10:24 UTC, jrasell commented on demo/vagrant/horizontal-app-scaling/jobs/haproxy.nomad
> +          address_mode = "driver"
I believe we can omit this, and allow the driver to dictate the address_mode for the check.

2021-01-04 11:13 UTC, trilom commented
Thanks for the feedback, I'll follow up with each one.

As I work through the remote example I realize the authors intent of the shared files more.

For example in the remote demo, the shared files are used exclusively by the azure demo, but ignored by the aws demo.  In this demo the other dashboard is mentioned but ultimately never included anywhere from the shared code.

Once I finish up using the remote part for learning I'll circle back to clean up what you have indicated based on your feedback and my discovery.

2021-03-03 18:00 UTC, lgfa29 commented
Hi @trilom,

Thanks for this work, it was helpful to flag to us where things needed to change. Since we're moving our demos to their own repo, I moved these changes and finished the remaining work in https://github.com/hashicorp/nomad-autoscaler-demos/pull/3, with you as the co-author, and so I am going to close this one.

Thank you for the contribution once again!

2021-03-03 18:00 UTC, closed without merging