Add GCE Managed Instance Group target plugin
hashicorp/nomad-autoscaler pull request #353
Opened 2021-01-22 18:40 UTC by jsiebens

This PR adds a Google Compute Engine MIG target plugin, for the scaling a Nomad cluster clients on GCP via manipulating [Regional Managed Instance Groups](https://cloud.google.com/compute/docs/instance-groups/regional-migs).

2021-01-22 18:40 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/nomad-autoscaler?pullRequest=353)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/nomad-autoscaler?pullRequest=353)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/nomad-autoscaler?pullRequest=353).</sub>

2021-01-25 10:23 UTC, jrasell commented
Hi @jsiebens, thanks so much for this!

It will likely take us a little bit of time to test fully as we don't currently run within this provider for any of our testing. In the meantime, I hope to make a first pass review in the next day.

2021-01-26 15:43 UTC, jrasell requested changes
Thanks again for this @jsiebens, we are really looking forward to testing this and getting this available!

I have taken an initial pass and have made some fairly nit-picky comments/suggestions, other than those its looking good. A general comment I also noticed is that it would be nice where logging to use `GCE` over `gce` as it's an acronym.

2021-01-26 15:43 UTC, jrasell commented on plugins/builtin/target/gce-mig/main.go
> +// factory returns a new instance of the AWS ASG plugin.
copy/paste remnants?
```suggestion
// factory returns a new instance of the Google Cloud Engine MIG plugin.
```

2021-01-26 15:43 UTC, jrasell commented on plugins/builtin/target/gce-mig/plugin/gce.go
> +	"time"
nit: could the imports be separated; stdlib top and other below, with the two sections separated by a newline and each section sorted alphabetically?

2021-01-26 15:43 UTC, jrasell commented on plugins/builtin/target/gce-mig/plugin/gce.go
> +
```suggestion
```

2021-01-26 15:43 UTC, jrasell commented on plugins/builtin/target/gce-mig/plugin/gce.go
> +
```suggestion
```

2021-01-26 15:43 UTC, jrasell commented on plugins/builtin/target/gce-mig/plugin/gce.go
> +
```suggestion
```

2021-01-26 15:43 UTC, jrasell commented on plugins/builtin/target/gce-mig/plugin/gce.go
> +
```suggestion
```

2021-01-26 15:43 UTC, jrasell commented on plugins/builtin/target/gce-mig/plugin/gce.go
> +
```suggestion
```

2021-01-26 15:43 UTC, jrasell commented on plugins/builtin/target/gce-mig/plugin/gce.go
> +	// Terminate the detached instances.
Could this maybe be reworded? My understanding is that the instances do not need to be detached before calling terminate and that is all handled as part of the `DeleteInstances` call?

2021-01-26 15:43 UTC, jrasell commented on plugins/builtin/target/gce-mig/plugin/plugin.go
> +	"google.golang.org/api/compute/v1"
nit: could the imports be separated; stdlib top and other below, with the two sections separated by a newline and each section sorted alphabetically?

2021-01-26 15:43 UTC, jrasell commented on plugins/builtin/target/gce-mig/plugin/plugin_test.go
> +	"testing"
```suggestion
     "testing"
        
	"github.com/stretchr/testify/assert"
```

2021-01-26 15:43 UTC, jrasell commented on plugins/builtin/target/gce-mig/plugin/plugin.go
> +
```suggestion
```

2021-01-26 15:43 UTC, jrasell commented on plugins/builtin/target/gce-mig/plugin/plugin.go
> +
```suggestion
```

2021-02-01 08:41 UTC, jrasell reviewed
Hi @jsiebens , we managed to get round to testing this properly in a GCP env and it worked first time without any problems, so thanks again!

One point that we noticed was that GCP has both regional and zonal managed instance groups, which use different API calls. Currently the plugin supports regional MIGs, which is likely to be the most commonly used. We would like to add support for both types, potentially making the different API calls based on whether the target includes a region or zone parameter. The team are happy to undertake this work as a follow up, but I wanted to check whether you had the desire and time to add this change?

Another, potentially trickier addition which again we can add as a follow up, would be to have some confirmation methods which ensure the change of count completes successfully. Azure has this functionality as part of the SDK, with AWS we poll the scaling status until progress reaches 100. I have not had a chance to find the GCP MIG equivalent yet though.

I'd be interested in your thoughts. Thanks again!

2021-02-01 15:07 UTC, jsiebens commented
Hi @jrasell , thank you for the feedback, I'm glad the testing worked out well. :-)

I considered adding support for zonal MIGs, but thought it would be better to get some early feedback from the team. So here we are :-) 

I would be happy to add those changes to this PR. I'll try to find some time in the coming days and also have a closer look at the second point you mentioned.

Of course, if the team wants to have the changes sooner, don't hesitate to undertake the work.

2021-02-05 00:04 UTC, lgfa29 approved these changes
Thanks for the PR @jsiebens!

I tested the new zone MIGs and it all worked well 🙂  

I pushed a few small changes for some small typos and also merged `master` to fix an annoying conflict in `go.sum`.

2021-02-05 23:26 UTC, merged