adding oldest_create_index
hashicorp/nomad-autoscaler pull request #961
Opened 2024-08-26 17:53 UTC by flipyap

2024-09-23 14:10 UTC, tgross commented
Hi @flipyap! We're going to take a look at this soon!

(Internal ref: https://hashicorp.atlassian.net/browse/NET-10944)

2024-09-27 14:51 UTC, tgross requested changes
Hi @flipyap! I've left some minor comments but otherwise this looks great! Can you add a line to the [CHANGELOG.md](https://github.com/hashicorp/nomad-autoscaler/blob/main/CHANGELOG.md#unreleased) as well?

Once this ships, I'll follow-up with a docs PR [here]( website/content/tools/autoscaling/concepts/policy-eval/node-selector-strategy.mdx) in the main Nomad repo.

2024-09-27 14:51 UTC, tgross commented on sdk/helper/scaleutils/nodeselector/oldest_create_index_test.go
> +	assert.Equal(t, "oldest_create_index", newOldestCreateIndexClusterScaleInNodeSelector().Name())
We're trying to gradually migrate Nomad repos to use `shoenig/test` over testify:

```suggestion
	must.Eq(t, "oldest_create_index", newOldestCreateIndexClusterScaleInNodeSelector().Name())
```

2024-09-27 14:51 UTC, tgross commented on sdk/helper/scaleutils/nodeselector/oldest_create_index_test.go
> +			assert.Equal(t, tc.expectedOutput, actualOutput, tc.inputNodes)
```suggestion
			must.Eq(t, tc.expectedOutput, actualOutput)
```

2024-09-27 14:51 UTC, tgross commented on sdk/helper/scaleutils/nodeselector/oldest_create_index_test.go
> +	"github.com/stretchr/testify/assert"
```suggestion
	"github.com/shoenig/test/must"
```

2024-10-01 13:22 UTC, tgross approved these changes
LGTM! Thanks @flipyap!

I've resolved merge conflicts with the changelog via the Github UI because you don't have edits enabled on your branch. Once CI is green I'll merge this.

2024-10-01 13:46 UTC, merged

2024-10-01 14:06 UTC, flipyap commented
Thanks!